title: Open Dataset User Guide Repository
description: This page is a convenient interface for accessing the contents of the repository. The source code and guides are available on the github repository linked at the bottom of the page
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
include:
  - docs
  - 'Current User Guides'
exclude:
  - README.md
navigation:
- text: Home
  internal: true
  url: ./
- text: Contributing
  internal: true
  url: docs/contributing.md
- text: New Guide Template
  internal: true
  url: docs/new_guide_template.md
